;13) Modificar el programa anterior para que también cuente minutos (00:00 - 59:59), pero que actualice la visualización en
;pantalla cada 10 segundos
CONT EQU 10H
COMP EQU 11H

EOI EQU 20H
IMR EQU 21H
INT1 EQU 25H

V_INT1 EQU 10
ORG 40
DW RUT_CLK

ORG 1000H
DEC_MIN DB 30H ;DECENAS DE MINUTOS XY:YY
MIN DB 30H ;MINUTOS YX:YY
DB 3AH; CARACTER :
DEC_SEC DB 30H ;DECENAS DE SEGUNDOS YY:XY
SEC DB 30H ;SEGUNDOS YY:YX
DB 10; LINE FEED
FIN DB ?
ORG 2000H
CLI
MOV AL, 11111101B
OUT IMR, AL ; PIC: registro IMR

MOV AL, V_INT1
OUT INT1, AL ; PIC: registro INT1

MOV AL, 0
OUT CONT, AL ; TIMER: registro CONT

MOV AL, 1
OUT COMP, AL ; TIMER: registro COMP
;00
MOV BX, OFFSET DEC_MIN
MOV AL, OFFSET FIN-OFFSET DEC_MIN
STI
LAZO: JMP LAZO
HLT

ORG 3000H
RUT_CLK: PUSH AX
INC DEC_SEC
CMP DEC_SEC, 36H; 36H=6 
;SI DEC_SEC TIENE UN CARACTER VALIDO (0-6) LO IMPRIME Y RESETEA EL CONTADOR
JNZ RESET
;SI SE PASO DE 6, LE PONE UN 0 (30H) Y EN CAMBIO INCREMENTA MIN 
MOV DEC_SEC, 30H
INC MIN
CMP MIN, 3AH
;SI MIN TIENE UN CARACTER VALIDO (0-9) LO IMPRIME Y RESETEA EL CONTADOR
JNZ RESET
;SI SE PASO DE 9, LE PONE UN 0 (30H) Y EN CAMBIO INCREMENTA DEC_MIN 
MOV MIN, 30H
INC DEC_MIN
CMP DEC_MIN, 36H
;SI DEC_MIN TIENE UN CARACTER VALIDO (0-6) LO IMPRIME Y RESETEA EL CONTADOR
JNZ RESET
;SINO LE PONE UN 0 (30H) 
MOV DEC_MIN, 30H

RESET: INT 7

MOV AL, 0
OUT CONT, AL

MOV AL, EOI
OUT EOI, AL

POP AX
IRET
END
