;14) * Implementar un reloj similar al utilizado en los partidos de básquet, que arranque y detenga su marcha al presionar
;sucesivas veces la tecla F10 y que finalice el conteo al alcanzar los 30 segundos.
CONT EQU 10H
COMP EQU 11H

EOI EQU 20H
IMR EQU 21H
INT0 EQU 24H
INT1 EQU 25H

V_INT0 EQU 5
V_INT1 EQU 10

ORG 20
DW RUT_F10

ORG 40
DW RUT_CLK

ORG 1000H
MSJ1 DB "TIEMPO FINALIZADO."
MSJ2 DB "ANOTACION."
FIN DB ?
TERMINAR DB 0

ORG 2000H
CLI
MOV AL, 11111100B
OUT IMR, AL ; PIC: registro IMR

MOV AL, V_INT0
OUT INT0, AL ; PIC: registro INT0

MOV AL, V_INT1
OUT INT1, AL ; PIC: registro INT1

MOV AL, 0
OUT CONT, AL ; TIMER: registro CONT

MOV AL, 30
OUT COMP, AL ; TIMER: registro COMP

STI
LAZO: CMP TERMINAR,0
JZ LAZO
HLT

ORG 3000H ;GESTOR DE INT0
RUT_F10:  INC TERMINAR 
;SALVO AX
PUSH AX
;ENMASCARO TODAS LAS INTERRUPCIONES
CLI
MOV AL,0FFH
OUT IMR,AL 
STI
;IMPRIME "ANOTACION."
MOV BX, OFFSET MSJ2
MOV AL, OFFSET FIN-OFFSET MSJ2
INT 7
;EOI
MOV AL, EOI
OUT EOI,AL
;SALVA AX
POP AX
IRET

ORG 3200H ;GESTOR DE INT1
RUT_CLK:  INC TERMINAR 
;SALVO AX
PUSH AX
;ENMASCARO TODAS LAS INTERRUPCIONES
CLI
MOV AL,0FFH
OUT IMR,AL 
STI
;IMPRIME "ANOTACION."
MOV BX, OFFSET MSJ1
MOV AL, OFFSET MSJ2-OFFSET MSJ1
INT 7
MOV AL, EOI
OUT EOI,AL

POP AX
IRET
END
