;7) * Escribir un programa que efectúe la suma de dos números (de un dígito cada uno) ingresados por teclado y muestre el
;resultado en la pantalla de comandos. Recordar que el código de cada caracter ingresado no coincide con el número que
;representa y que el resultado puede necesitar ser expresado con 2 dígitos.
ORG 1000H
MSJ1 DB " INGRESE UN NUMERO:"
MSJ2 DB " INGRESE OTRO NUMERO:"
ERROR DB "CARACTER INVALIDO."
FIN DB ?

ORG 1500H
NUM1 DB ?
NUM2 DB ?
RES DB 00H

ORG 2000H
MOV BX, OFFSET MSJ1 ;IMPRIME EL PRIMER MENSAJE
MOV AL, OFFSET  MSJ2-OFFSET MSJ1
INT 7
MOV BX, OFFSET NUM1;GUARDA EL PRIMER NUMERO
INT 6

CALL ES_NUM  ;FINALIZA EL PROGRAMA SI EL CARACTER INGRESADO NO ES UN NUMERO
CMP AL,0
JZ FINALIZAR

MOV BX, OFFSET MSJ2 ;IMPRIME EL SEGUNDO MENSAJE
MOV AL, OFFSET ERROR-OFFSET MSJ2
INT 7
MOV BX, OFFSET NUM2;GUARDA EL SEGUNDO NUMERO
INT 6

CALL ES_NUM  ;FINALIZA EL PROGRAMA SI EL CARACTER INGRESADO NO ES UN NUMERO
CMP AL,0
JZ FINALIZAR

MOV BX, OFFSET RES
MOV AL, 1

MOV AH, NUM1
ADD AH, NUM2
CMP AH, 6AH ;COMPRUEBA SI EL RESULTADO TIENE DOS DIGITOS 
JNC DOS_DIGITOS

SUB AH, 30H
MOV RES,AH
JMP IMPRIMIR

DOS_DIGITOS:
MOV RES,31H ;IMPRIME UN 1
INT 7
SUB AH,3AH ;OBTIENE EL CODIGO ASCII DEL SEGUNDO NUMERO A IMPRIMIR
MOV RES,AH

IMPRIMIR:
INT 7


FINALIZAR: INT 0

ORG 3000H
ES_NUM: MOV AH,[BX]
MOV AL,00H
CMP AH,30H
JS RETORNAR
CMP AH,3AH
JNS RETORNAR
MOV AL,0FFH
RETORNAR:
MOV AH,00H
RET
END


