;8) Escribir un programa que efectúe la resta de dos números (de un dígito cada uno) ingresados por teclado y muestre el
;resultado en la pantalla de comandos. Antes de visualizarlo el programa debe verificar si el resultado es positivo o negativo
;y anteponer al valor el signo correspondiente
ORG 1000H
MSJ1 DB " INGRESE UN NUMERO:"
MSJ2 DB " INGRESE OTRO NUMERO:"
ERROR DB "CARACTER INVALIDO."
FIN DB ?

ORG 1500H
NUM1 DB ?
NUM2 DB ?
RES DB 00H

ORG 2000H
MOV BX, OFFSET MSJ1 ;IMPRIME EL PRIMER MENSAJE
MOV AL, OFFSET  MSJ2-OFFSET MSJ1
INT 7
MOV BX, OFFSET NUM1;GUARDA EL PRIMER NUMERO
INT 6

CALL ES_NUM  ;FINALIZA EL PROGRAMA SI EL CARACTER INGRESADO NO ES UN NUMERO
CMP AL,0
JZ FINALIZAR

MOV BX, OFFSET MSJ2 ;IMPRIME EL SEGUNDO MENSAJE
MOV AL, OFFSET ERROR-OFFSET MSJ2
INT 7
MOV BX, OFFSET NUM2;GUARDA EL SEGUNDO NUMERO
INT 6

CALL ES_NUM  ;FINALIZA EL PROGRAMA SI EL CARACTER INGRESADO NO ES UN NUMERO
CMP AL,0
JZ FINALIZAR

MOV BX, OFFSET RES
MOV AL, 1

MOV AH, NUM1
CMP AH, NUM2 ;REVISO SI EL RESULTADO ES NEGATIVO O NO 
JC NEGATIVO

SUB AH,NUM2
JMP IMPRIMIR

NEGATIVO:
MOV RES,2DH ;IMPRIME UN -
INT 7
MOV AH,NUM2
SUB AH,NUM1 ;OBTIENE EL CODIGO ASCII DEL SEGUNDO NUMERO A IMPRIMIR

IMPRIMIR:
MOV RES,AH
ADD RES, 30H
INT 7


FINALIZAR: INT 0

ORG 3000H
ES_NUM: MOV AH,[BX]
MOV AL,00H
CMP AH,30H
JS RETORNAR
CMP AH,3AH
JNS RETORNAR
MOV AL,0FFH
RETORNAR:
MOV AH,00H
RET
END



