;9) Escribir un programa que aguarde el ingreso de una clave de cuatro caracteres por teclado sin visualizarla en pantalla. En
;caso de coincidir con una clave predefinida (y guardada en memoria) que muestre el mensaje "Acceso permitido", caso
;contrario el mensaje "Acceso denegado".
ORG 1000H
MSJ1 DB "INGRESE LA CLAVE:"
MSJ2 DB "ACCESO PERMITIDO."
MSJ3 DB "ACCESO DENEGADO."
FIN DB ?

ORG 1500H
CLAVE DB "1122"
ENTRADA DB ?


ORG 2000H
MOV BX, OFFSET MSJ1 ;IMPRIME EL PRIMER MENSAJE
MOV AL, OFFSET  MSJ2-OFFSET MSJ1
INT 7
MOV CL,4
MOV BX, OFFSET ENTRADA;GUARDA LA ENTRADA
INPUT:
INT 6
INC BX
DEC CL
JNZ INPUT

MOV CX,0
LOOP:
MOV BX, OFFSET CLAVE
ADD BX,CX
MOV DH,[BX] ;GUARDO UN CARACTER DE LA CLAVE
ADD BX,4
MOV DL,[BX] ;GUARDO UN CARACTER INGRESADO
CMP DH,DL
JNZ DENEGADO
CMP CX,3
JZ PERMITIDO
INC CX
JMP LOOP


PERMITIDO:
MOV BX, OFFSET MSJ2 ;IMPRIME EL PRIMER MENSAJE
MOV AL, OFFSET MSJ3-OFFSET MSJ2
JMP IMPRIMIR
DENEGADO:
MOV BX, OFFSET MSJ3 ;IMPRIME EL SEGUNDO MENSAJE
MOV AL, OFFSET FIN-OFFSET MSJ3



IMPRIMIR:
INT 7


FINALIZAR: INT 0

ORG 3000H
ES_NUM: MOV AH,[BX]
MOV AL,00H
CMP AH,30H
JS RETORNAR
CMP AH,3AH
JNS RETORNAR
MOV AL,0FFH
RETORNAR:
MOV AH,00H
RET
END



