;c) * Escribir un programa que solicita el ingreso de cinco caracteres por teclado y los envía de a uno por
;vez a la impresora a través de la PIO a medida que se van ingresando. No es necesario mostrar los
;caracteres en la pantalla.
PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H

ORG 1000H
STR DB "Ingrese un numero:"
FIN DB ?

ORG 1500H
NUM DB ?

ORG 2000H
;CONFIGURACION DE PA 
MOV AL,1
OUT CA,AL
;CONFIGURACION DE PB 
MOV AL, 0
OUT CB, AL
;CANTIDAD DE CARACTERES A INGRESAR
MOV CL, 5
;MENSAJE A MOSTRAR
MOV BX, OFFSET STR
MOV AL, OFFSET FIN-OFFSET STR
;MAIN LOOP
LOOP:
;IMPRIMIR  MENSAJE
INT 7
;INGRESO DE NUMERO
MOV BX,OFFSET NUM
INT 6
;CONSULTA DE ESTADO
IN AL,PA
AND AL,1
JNZ LOOP
;IMPRIMO CARACTER
MOV AL,[BX]
OUT PB,AL
CALL SEND_STROBE
;INGRESE UN NUMERO
MOV BX, OFFSET STR
MOV AL, OFFSET FIN-OFFSET STR
;AUMENTO BX REDUZCO CL
DEC CL
JNZ LOOP
HLT

ORG 3000H
SEND_STROBE:
PUSH AX
IN AL,PA
AND AL,11111101B
OUT PA,AL
OR AL,00000010B
OUT PA,AL
POP AX
RET
END
