;c) * Escribir un programa que imprime “UNIVERSIDAD NACIONAL DE LA PLATA” en la impresora a
;través del HAND-SHAKE. La comunicación se establece por interrupciones emitidas desde el
;HAND-SHAKE cada vez que la impresora se desocupa.
EOI EQU 20H
IMR EQU 21H
INT2 EQU 26H
ID_INT2 EQU 10
DATO EQU 40H
ESTADO EQU 41H

ORG 40
DW RUT_HS

ORG 1000H
STR DB "INGENIERIA E INFORMATICA"
FIN DB ?
TERMINAR DB 0

ORG 2000H
;CONFIGURACION ESTADO
IN AL,ESTADO
OR AL,10000000B; I->1
OUT ESTADO,AL
;IMPRESION
MOV BX,OFFSET STR
MOV CL,OFFSET FIN-OFFSET STR
;CONFIGURACION PIC
CLI
MOV AL, 11111011B
OUT IMR,AL

MOV AL,ID_INT2
OUT INT2,AL
STI
LOOP: CMP TERMINAR,0
JZ LOOP
INT 0

ORG 3000H
RUT_HS:
PUSH AX
;IMPRESION DEL CARACTER
MOV AL,[BX]
OUT DATO,AL
;CX BX
INC BX
DEC CL
JNZ RETORNAR
MOV TERMINAR,1
;DESABILITAR INTERRUPCIONES
CLI
MOV AL,0FFH
OUT IMR,AL
STI
RETORNAR:
;EOI
MOV AL, EOI
OUT EOI,AL
;SALVAR AX
POP AX
IRET
END
