#Robocode window sizes
#Wed Aug 26 17:55:30 ART 2026
net.sf.robocode.ui.dialog.RobocodeFrame=0,0,923,699
net.sf.robocode.ui.dialog.NewBattleDialog=358,58,842,651
net.sf.robocode.ui.dialog.PreferencesDialog=146,184,1063,344
